### ISSUE TITLE
IndexError when running demo data

### ISSUE THREAD

**Issue by toddknutson** [PacificBiosciences/pangu#2]
Hi,

I was testing your tool and came across an error that I cannot resolve. I downloaded the hg38 ref genome from UCSC, isolated only the chr22 contig, and generated a new index (as described in your readme file). I edited the `genes/CYP2D6.yaml` file with the path to my new chr22 ref file. Then I tried running the tool using the demo data, which returned an error. Can you suggest any solution? Thanks!!

```
cd pangu/demo_data
../pangu -m amplicon -p out_dir --verbose -x --logLevel DEBUG  NA17244_amp_hifi.GRCh38.bam



2022-12-13 15:45:48,035 | INFO | Processing NA17244_amp_hifi.GRCh38.bam
2022-12-13 15:45:51,318 | INFO | Identifying SV signatures
2022-12-13 15:45:52,153 | INFO | Phasing and Calling Alleles
2022-12-13 15:45:52,154 | DEBUG | Calling noSV
2022-12-13 15:45:52,155 | DEBUG | Attempting to phase noSV reads
2022-12-13 15:45:52,155 | DEBUG | Reseting HP for 54 noSV  reads
2022-12-13 15:45:52,412 | DEBUG | Positions used for read clustering: [42123210, 42123218, 42123225, 42123235, 42123236, 42123237, 42123238, 42123242, 42123243, 42123251, 42123253, 42123299, 42123307, 42123310, 42123311, 42123538, 42123630, 42124105, 42124797, 42125979, 42126131, 42126309, 42126389, 42127000, 42127206, 42127208, 42127940, 42128693, 42128944, 42129795, 42129808, 42129818, 42130546, 42130558, 42130559, 42130564, 42130568, 42130570, 42130577, 42130691, 42131468, 42131530, 42131790, 42132216, 42132374, 42132560]
/home/lmnp/todd/.conda/envs/cyp/lib/python3.9/site-packages/scikit_learn-1.2.0-py3.9-linux-x86_64.egg/sklearn/cluster/_kmeans.py:870: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  warnings.warn(
2022-12-13 15:45:59,293 | DEBUG | Calling hybrid
2022-12-13 15:45:59,297 | WARNING | Low-coverage hybrid called: ('*78',) (1<10)
2022-12-13 15:45:59,297 | WARNING | Low-coverage hybrid called: ('*80',) (1<10)
2022-12-13 15:45:59,297 | DEBUG | Calling duplicate
2022-12-13 15:45:59,297 | DEBUG | Attempting to phase duplicate reads
2022-12-13 15:45:59,298 | DEBUG | Reseting HP for 27 duplicate  reads
2022-12-13 15:45:59,434 | DEBUG | Positions used for read clustering: [42123538, 42123630, 42124105, 42124797, 42125979, 42126131, 42126309, 42127000, 42127206, 42127208, 42127940, 42128693, 42128944, 42129808, 42129818, 42130546, 42130558, 42130559, 42130568, 42130570, 42130577, 42131468, 42131530, 42131790, 42132216, 42132374, 42132560]
/home/lmnp/todd/.conda/envs/cyp/lib/python3.9/site-packages/scikit_learn-1.2.0-py3.9-linux-x86_64.egg/sklearn/cluster/_kmeans.py:870: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  warnings.warn(
2022-12-13 15:46:05,617 | DEBUG | Reseting HP for 16 noSV  reads
2022-12-13 15:46:05,708 | DEBUG | No variable positions found for 16 noSV reads. Exiting updateHaplotypes
2022-12-13 15:46:05,709 | DEBUG | Reseting HP for 31 duplicate  reads
2022-12-13 15:46:05,843 | DEBUG | No variable positions found for 31 duplicate reads. Exiting updateHaplotypes
2022-12-13 15:46:05,855 | DEBUG | Reseting HP for 11 noSV  reads
2022-12-13 15:46:05,914 | DEBUG | No variable positions found for 11 noSV reads. Exiting updateHaplotypes
2022-12-13 15:46:05,916 | DEBUG | Reseting HP for 23 duplicate  reads
2022-12-13 15:46:06,011 | DEBUG | No variable positions found for 23 duplicate reads. Exiting updateHaplotypes
2022-12-13 15:46:06,012 | DEBUG | Calling deletion
2022-12-13 15:46:06,013 | WARNING | Low Coverage call: deletion (1<10)
2022-12-13 15:46:06,013 | DEBUG | Alleles Identified: {'noSV': {'noSV_2': ('*2', '*34', '*39'), 'noSV_3': ('*4', '*10', '*39', '*74')}, 'hybrid': {'hybrid_0': ()}, 'duplicate': {'duplicate_2': ('*2', '*34', '*39'), 'duplicate_3': ('*4', '*10', '*39', '*74')}}
2022-12-13 15:46:06,013 | INFO | Calling Diplotype
2022-12-13 15:46:06,013 | WARNING | UNKNOWN hybrid breakpoint
2022-12-13 15:46:06,013 | ERROR | Extra haplotypes called: [('*2x2', ['duplicate_2', 'noSV_2']), ('*4x2', ['duplicate_3', 'noSV_3']), ('unknown', ['hybrid_0'])]
2022-12-13 15:46:06,013 | INFO | Diplotype called: CYP2D6 *2x2/*4x2/unknown
2022-12-13 15:46:15,968 | WARNING | 4272 bases in variant region with coverage < 10
Traceback (most recent call last):
  File "/scratch.global/todd_scratch/pangu/demo_data/../pangu", line 121, in <module>
    starTyper = main( parser )
  File "/scratch.global/todd_scratch/pangu/demo_data/../pangu", line 61, in main
    typer.run( bamfile, vcffile )
  File "/scratch.global/todd_scratch/pangu/src/cyp2d6_typer.py", line 76, in run
    self.report.append( self.makeReport() )
  File "/scratch.global/todd_scratch/pangu/src/cyp2d6_typer.py", line 272, in makeReport
    count = sum( 2 if 'x2' in calls[0] else 1 for _,alleles in self.diplotype.calls.items() for _,calls in alleles.items() )
  File "/scratch.global/todd_scratch/pangu/src/cyp2d6_typer.py", line 272, in <genexpr>
    count = sum( 2 if 'x2' in calls[0] else 1 for _,alleles in self.diplotype.calls.items() for _,calls in alleles.items() )
IndexError: tuple index out of range
```

**Comment by jrharting** [comment]
Thanks for trying this out -- looks like you got it installed correctly, but this is a bug.  I am planning to push an updated version in the next couple days.  I will get this fixed and include it in the update!
