### ISSUE TITLE
Error while installing pangu

### ISSUE THREAD

**Issue by Tintest** [PacificBiosciences/pangu#5]
Hello,

I am writing to you because I am encountering the following error when trying to install pangu. 

```shell
pip3 --version

pip 23.2.1 from /srv/scratch/testardqu/miniconda3/lib/python3.11/site-packages/pip (python 3.11)

git clone https://github.com/PacificBiosciences/pangu.git
cd pangu
pip install .
Cloning into 'pangu'...
remote: Enumerating objects: 174, done.
remote: Counting objects: 100% (174/174), done.
remote: Compressing objects: 100% (108/108), done.
remote: Total 174 (delta 82), reused 142 (delta 50), pack-reused 0
Receiving objects: 100% (174/174), 20.83 MiB | 20.20 MiB/s, done.
Resolving deltas: 100% (82/82), done.
Processing /home/chu-lyon.fr/testardqu/pangu
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [50 lines of output]
      WARNING setuptools_scm._integration.setuptools pyproject.toml does not contain a tool.setuptools_scm section
      configuration error: `project.dependencies[3]` must be pep508
      DESCRIPTION:
          Project dependency specification according to PEP 508

      GIVEN VALUE:
          "pandas=1.5"

      OFFENDING RULE: 'format'

      DEFINITION:
          {
              "$id": "#/definitions/dependency",
              "title": "Dependency",
              "type": "string",
              "format": "pep508"
          }
      Traceback (most recent call last):
        File "/srv/scratch/testardqu/miniconda3/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/srv/scratch/testardqu/miniconda3/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/srv/scratch/testardqu/miniconda3/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "/srv/scratch/testardqu/tmp/pip-build-env-cap7ijl2/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 325, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/srv/scratch/testardqu/tmp/pip-build-env-cap7ijl2/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 295, in _get_build_requires
          self.run_setup()
        File "/srv/scratch/testardqu/tmp/pip-build-env-cap7ijl2/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 311, in run_setup
          exec(code, locals())
        File "<string>", line 1, in <module>
        File "/srv/scratch/testardqu/tmp/pip-build-env-cap7ijl2/overlay/lib/python3.11/site-packages/setuptools/__init__.py", line 103, in setup
          return distutils.core.setup(**attrs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/srv/scratch/testardqu/tmp/pip-build-env-cap7ijl2/overlay/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 159, in setup
          dist.parse_config_files()
        File "/srv/scratch/testardqu/tmp/pip-build-env-cap7ijl2/overlay/lib/python3.11/site-packages/setuptools/dist.py", line 627, in parse_config_files
          pyprojecttoml.apply_configuration(self, filename, ignore_option_errors)
        File "/srv/scratch/testardqu/tmp/pip-build-env-cap7ijl2/overlay/lib/python3.11/site-packages/setuptools/config/pyprojecttoml.py", line 66, in apply_configuration
          config = read_configuration(filepath, True, ignore_option_errors, dist)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/srv/scratch/testardqu/tmp/pip-build-env-cap7ijl2/overlay/lib/python3.11/site-packages/setuptools/config/pyprojecttoml.py", line 127, in read_configuration
          validate(subset, filepath)
        File "/srv/scratch/testardqu/tmp/pip-build-env-cap7ijl2/overlay/lib/python3.11/site-packages/setuptools/config/pyprojecttoml.py", line 55, in validate
          raise ValueError(f"{error}\n{summary}") from None
      ValueError: invalid pyproject.toml config: `project.dependencies[3]`.
      configuration error: `project.dependencies[3]` must be pep508
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

I tried aswell to install the latest commit locally, but also pangu v0.2.3, pangu v0.2.2. I've also tried installing it in a Singularity image with the following recipe.

```shell
cat Singularity.def
Bootstrap: docker
From: continuumio/miniconda
Stage: spython-base

%labels
tags="Genomics"
%post

################## CONDA TOOLS ######################

conda update -n base conda \
&& conda config --add channels conda-forge \
&& conda config --add channels bioconda \
&& conda install -c bioconda python=3.9 setuptools pip git pysam=0.19.1 pyyaml numpy=1.23.3 pandas=1.5.0 scipy scikit-learn mappy=2.24

git clone https://github.com/PacificBiosciences/pangu.git \
&& cd pangu \
&& pip install .
%runscript
exec /bin/bash "$@"
%startscript
exec /bin/bash "$@"
```

But same result. Can you help me?

Regards.

**Comment by jrharting** [comment]
Hi, thanks for reporting this.  I am preparing a fix that will address this as well as another bug and should be posting it in the next day or so.  In the mean time, the quick fix is to edit your local pyproject.toml file.  In the dependencies, it should have "pandas==1.5" (two "="), but there is one missing.  The other bug fix should remove the need to restrict pandas to v1.5 and allow for v2 to work.

**Comment by Tintest** [comment]
Hello, 

Indeed, it works better with "==" ... Sorry for the inconvenience. 

Regards.
